# Generated by Django 3.2.20 on 2023-10-06 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Max 100 character', max_length=100, verbose_name='Title of the author')),
                ('description', models.TextField(blank=True, help_text='Max 1000 character', max_length=1000, null=True, verbose_name='Description of the author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(help_text='Just media', upload_to='blog_media', verbose_name='Medias of the blog ')),
                ('title', models.CharField(help_text='Max 100 character', max_length=100, verbose_name='Title of the blog')),
                ('description', models.TextField(help_text='Max 1000 character', verbose_name='Descripyion of the blog ')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='blog.author', verbose_name='Author of the blog')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='BlogType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('types', models.CharField(max_length=20, verbose_name='Type of the blog')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='Name of the commenter')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('title', models.CharField(max_length=100, verbose_name='Title of the comment')),
                ('comments', models.TextField()),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to='blog.blogs')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='types',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogtype'),
        ),
    ]
