# Generated by Django 3.2.20 on 2023-10-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='description_az',
            field=models.TextField(help_text='Max 1000 character', null=True, verbose_name='Descripyion of the blog '),
        ),
        migrations.AddField(
            model_name='blogs',
            name='description_en',
            field=models.TextField(help_text='Max 1000 character', null=True, verbose_name='Descripyion of the blog '),
        ),
    ]
