# Generated by Django 3.2.20 on 2023-10-14 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20231014_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='description_az',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='description_en',
        ),
    ]
