# Generated by Django 3.2.20 on 2023-10-11 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_reviewcomment'),
        ('order', '0002_auto_20231012_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basketitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_basket_item', to='product.productversion'),
        ),
    ]
